/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CheckoutsIndexRouteImport } from "./routes/checkouts/index";
import { Route as CheckoutsCheckoutIdRouteImport } from "./routes/checkouts/$checkoutId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutsIndexRoute = CheckoutsIndexRouteImport.update({
  id: "/checkouts/",
  path: "/checkouts/",
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutsCheckoutIdRoute = CheckoutsCheckoutIdRouteImport.update({
  id: "/checkouts/$checkoutId",
  path: "/checkouts/$checkoutId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/checkouts/$checkoutId": typeof CheckoutsCheckoutIdRoute;
  "/checkouts/": typeof CheckoutsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/checkouts/$checkoutId": typeof CheckoutsCheckoutIdRoute;
  "/checkouts": typeof CheckoutsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/checkouts/$checkoutId": typeof CheckoutsCheckoutIdRoute;
  "/checkouts/": typeof CheckoutsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/checkouts/$checkoutId" | "/checkouts/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/checkouts/$checkoutId" | "/checkouts";
  id: "__root__" | "/" | "/checkouts/$checkoutId" | "/checkouts/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CheckoutsCheckoutIdRoute: typeof CheckoutsCheckoutIdRoute;
  CheckoutsIndexRoute: typeof CheckoutsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/checkouts/": {
      id: "/checkouts/";
      path: "/checkouts";
      fullPath: "/checkouts/";
      preLoaderRoute: typeof CheckoutsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/checkouts/$checkoutId": {
      id: "/checkouts/$checkoutId";
      path: "/checkouts/$checkoutId";
      fullPath: "/checkouts/$checkoutId";
      preLoaderRoute: typeof CheckoutsCheckoutIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutsCheckoutIdRoute: CheckoutsCheckoutIdRoute,
  CheckoutsIndexRoute: CheckoutsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
